name: Deploy generated api docs to production.
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
    push:
        branches:
            - release

    workflow_dispatch:

jobs:
    Deploy-Production:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Vercel CLI
              run: npm install --global vercel@latest
              # Run npm install for doc gen
            - name: Run npm install
              run: npm install --legacy-peer-deps
              # Run doc gen. this will create a static side inside ./docs folder
            - name: Run doc gen
              run: npm run docgen

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.TS_CHART_SDK_DOCS_VERCEL_TOKEN }}

            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy ./docs --prod --token=${{ secrets.TS_CHART_SDK_DOCS_VERCEL_TOKEN }}
